import { Inter } from "next/font/google";
import "./globals.css";
import HomeButton from "./components/HomeButton";
// import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Honeycomb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <NavBar /> */}
        <HomeButton />
        {children}
        </body>
    </html>
  );
}


